### ISSUE TITLE
m2 macbook 执行 sudo ./install.sh 报错

### ISSUE THREAD

**Issue by easy033** [DeepInsight-AI/DeepBI#131]
#0 68.09   Downloading python_dotenv-0.19.2-py2.py3-none-any.whl (17 kB)
#0 68.88 Collecting pytz==2023.3.post1
#0 69.07   Downloading pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
#0 69.58 Collecting PyYAML==5.4
#0 69.68   Downloading PyYAML-5.4.tar.gz (174 kB)
#0 69.89   Installing build dependencies: started
#0 73.85   Installing build dependencies: finished with status 'done'
#0 73.85   Getting requirements to build wheel: started
#0 73.98   ERROR: Command errored out with exit status 1:
#0 73.98    command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpm2977m3b
#0 73.98        cwd: /tmp/pip-install-qpz638ez/pyyaml
#0 73.98   Complete output (48 lines):
#0 73.98   running egg_info
#0 73.98   writing lib3/PyYAML.egg-info/PKG-INFO
#0 73.98   writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
#0 73.98   writing top-level names to lib3/PyYAML.egg-info/top_level.txt
#0 73.98   Traceback (most recent call last):
#0 73.98     File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
#0 73.98       main()
#0 73.98     File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
#0 73.98       json_out['return_val'] = hook(**hook_input['kwargs'])
#0 73.98     File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
#0 73.98       return hook(config_settings)
#0 73.98     File "/tmp/pip-build-env-qx6ueobv/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
#0 73.98       return self._get_build_requires(config_settings, requirements=['wheel'])
#0 73.98     File "/tmp/pip-build-env-qx6ueobv/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
#0 73.98       self.run_setup()
#0 73.98     File "/tmp/pip-build-env-qx6ueobv/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
#0 73.98       exec(code, locals())
#0 73.98     File "<string>", line 271, in <module>

**Comment by xph906** [comment]
The same error when installing PyYAML.
